import React, { useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import * as THREE from "three";
import "./style.css";

type Screen = "menu" | "game" | "result";

function App() {
  const [screen, setScreen] = useState<Screen>("menu");
  const [best, setBest] = useState(() => Number(localStorage.getItem("skyfall-best") || 0));
  const [score, setScore] = useState(0);
  const start = () => { setScore(0); setScreen("game"); };
  return <main>{screen === "menu" && <Menu best={best} onStart={start}/>} {screen === "game" && <Game onEnd={(value) => { const next=Math.max(best,value); setBest(next); localStorage.setItem("skyfall-best",String(next)); setScore(value); setScreen("result"); }}/>} {screen === "result" && <Result score={score} onAgain={start} onMenu={() => setScreen("menu")}/>}</main>;
}
function Menu({best,onStart}:{best:number;onStart:()=>void}) { return <section className="menu"><div className="orb">✦</div><h1>SKYFALL</h1><p>Drop into the storm. Outlast the horizon.</p><button onClick={onStart}>START OFFLINE DROP</button><div className="card">BEST SURVIVAL <b>{best}s</b></div><small>Original offline arcade survival · no account · no internet</small></section>; }
function Result({score,onAgain,onMenu}:{score:number;onAgain:()=>void;onMenu:()=>void}) { return <section className="menu"><h2>DROP COMPLETE</h2><div className="score">{score}<small> seconds survived</small></div><button onClick={onAgain}>DROP AGAIN</button><button className="secondary" onClick={onMenu}>MAIN MENU</button></section>; }
function Game({onEnd}:{onEnd:(score:number)=>void}) {
 const ref=useRef<HTMLCanvasElement>(null); const [time,setTime]=useState(0); const [hp,setHp]=useState(100);
 useEffect(()=>{ const canvas=ref.current!; const renderer=new THREE.WebGLRenderer({canvas,antialias:true}); renderer.setPixelRatio(Math.min(devicePixelRatio,1.5)); const scene=new THREE.Scene(); scene.background=new THREE.Color(0x08152b); scene.fog=new THREE.Fog(0x08152b,25,100); const camera=new THREE.PerspectiveCamera(60,1,.1,200); camera.position.set(0,8,14); camera.lookAt(0,0,0); scene.add(new THREE.HemisphereLight(0x9edcff,0x101020,2)); const sun=new THREE.DirectionalLight(0xffffff,2); sun.position.set(4,10,5); scene.add(sun); const ground=new THREE.Mesh(new THREE.CircleGeometry(45,48),new THREE.MeshStandardMaterial({color:0x174052})); ground.rotation.x=-Math.PI/2; scene.add(ground); const player=new THREE.Mesh(new THREE.ConeGeometry(.7,1.8,6),new THREE.MeshStandardMaterial({color:0x36d1dc,emissive:0x063c52})); player.position.y=1; scene.add(player); const hazards:Array<THREE.Mesh>=[]; for(let i=0;i<18;i++){const m=new THREE.Mesh(new THREE.IcosahedronGeometry(.45+Math.random()*.5),new THREE.MeshStandardMaterial({color:0xff4f70,emissive:0x481020})); m.position.set((Math.random()-.5)*28,.7,(Math.random()-.5)*28); scene.add(m); hazards.push(m);} let start=performance.now(), raf=0, last=0; const keys=new Set<string>(); const down=(e:KeyboardEvent)=>keys.add(e.code), up=(e:KeyboardEvent)=>keys.delete(e.code); addEventListener("keydown",down); addEventListener("keyup",up); const resize=()=>{const w=canvas.clientWidth||innerWidth,h=canvas.clientHeight||innerHeight; renderer.setSize(w,h,false); camera.aspect=w/h;camera.updateProjectionMatrix();}; addEventListener("resize",resize); resize(); const loop=(now:number)=>{const dt=Math.min(.05,(now-last)/1000||0);last=now; const elapsed=(now-start)/1000; setTime(Math.floor(elapsed)); let x=0,z=0;if(keys.has("ArrowLeft")||keys.has("KeyA"))x-=1;if(keys.has("ArrowRight")||keys.has("KeyD"))x+=1;if(keys.has("ArrowUp")||keys.has("KeyW"))z-=1;if(keys.has("ArrowDown")||keys.has("KeyS"))z+=1;player.position.x=Math.max(-18,Math.min(18,player.position.x+x*dt*10));player.position.z=Math.max(-18,Math.min(18,player.position.z+z*dt*10));hazards.forEach((m,i)=>{m.rotation.x+=dt; m.rotation.y+=dt*(i%2?1:-1); if(m.position.distanceTo(player.position)<1.2)setHp(v=>Math.max(0,v-dt*22));}); camera.lookAt(player.position.x,0,player.position.z);renderer.render(scene,camera);if(elapsed>=60){onEnd(60);return;}if(hp<=0){onEnd(Math.floor(elapsed));return;}raf=requestAnimationFrame(loop);};raf=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(raf);removeEventListener("keydown",down);removeEventListener("keyup",up);removeEventListener("resize",resize);renderer.dispose();};},[onEnd,hp]); return <section className="game"><canvas ref={ref}/><div className="hud"><b>{time}s</b><span> SURVIVE THE STORM</span><div className="bar"><i style={{width:`${hp}%`}}/></div><small>WASD / ARROWS TO MOVE</small></div></section>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
